-------------------------  Command 1   -------------------------

AddEventHandler('chatMessage', function(source, name, msg)
	sm = stringsplit(msg, " ");
	if sm[1] == Config.Command1 then
		CancelEvent()
		if msg ~= nil and Config.Discordis and Config.Command1responseis and Config.Command1global then
     		local discordmessage = {
            	{
            		["type"] = "rich",
					["title"] = Config.Command1,
					["color"] = Config.color,
                	["description"] = msg,
                	["footer"] = {
                	["text"] = "Generated By: "..name.. "."
                	}
            	}
        	}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source, Config.Command1response)
end
		if msg ~= nil and Config.Discordis and Config.Command1responseis and Config.Command1global == false then
			local discordmessage = {
	   			{
		   			["type"] = "rich",
		   			["title"] = Config.Command1,
		   			["color"] = Config.color,
		   			["description"] = msg,
		   			["footer"] = {
		   			["text"] = "Generated By: "..name.. "."
		  			}
				}
  			}
  			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
  			TriggerClientEvent('chatMessage', source, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
  			TriggerClientEvent('chatMessage', source, Config.Command1response)
end
		if msg ~= nil and Config.Discordis and Config.Command1responseis == false and Config.Command1global then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command1,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..name.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
end
		if msg ~= nil and Config.Discordis and Config.Command1responseis == false and Config.Command1global == false then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command1,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..name.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', source, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command1responseis and Config.Command1global then
			TriggerClientEvent('chatMessage', -1, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command1response)
end
		if Config.Discordis == false and Config.Command1responseis and Config.Command1global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command1response)
end
		if Config.Discordis == false and Config.Command1responseis == false and Config.Command1global then
			TriggerClientEvent('chatMessage', -1, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command1responseis == false and Config.Command1global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command1Subject .. name, Config.Command1color, string.sub(msg,5))
		end
	end 
 end)

 -------------------------  Command 2   -------------------------

 AddEventHandler('chatMessage', function(source, name, msg)
	sm = stringsplit(msg, " ");
	if sm[1] == Config.Command2 then
		CancelEvent()
		if msg ~= nil and Config.Discordis and Config.Command2responseis and Config.Command2global then
     		local discordmessage = {
            	{
            		["type"] = "rich",
					["title"] = Config.Command2,
					["color"] = Config.color,
                	["description"] = msg,
                	["footer"] = {
                	["text"] = "Generated By: "..source.. "."
                	}
            	}
        	}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source, Config.Command1response)
end
		if msg ~= nil and Config.Discordis and Config.Command2responseis and Config.Command2global == false then
			local discordmessage = {
	   			{
		   			["type"] = "rich",
		   			["title"] = Config.Command2,
		   			["color"] = Config.color,
		   			["description"] = msg,
		   			["footer"] = {
		   			["text"] = "Generated By: "..source.. "."
		  			}
				}
  			}
  			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
  			TriggerClientEvent('chatMessage', source, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
  			TriggerClientEvent('chatMessage', source, Config.Command2response)
end
		if msg ~= nil and Config.Discordis and Config.Command2responseis == false and Config.Command2global then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command2,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
end
		if msg ~= nil and Config.Discordis and Config.Command2responseis == false and Config.Command2global == false then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command2,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', source, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command2responseis and Config.Command2global then
			TriggerClientEvent('chatMessage', -1, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command2response)
end
		if Config.Discordis == false and Config.Command2responseis and Config.Command2global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command2response)
end
		if Config.Discordis == false and Config.Command2responseis == false and Config.Command2global then
			TriggerClientEvent('chatMessage', -1, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command2responseis == false and Config.Command2global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command2Subject .. name, Config.Command2color, string.sub(msg,5))
		end
	end 
 end)

 -------------------------  Command 3   -------------------------

 AddEventHandler('chatMessage', function(source, name, msg)
	sm = stringsplit(msg, " ");
	if sm[1] == Config.Command3 then
		CancelEvent()
		if msg ~= nil and Config.Discordis and Config.Command3responseis and Config.Command3global then
     		local discordmessage = {
            	{
            		["type"] = "rich",
					["title"] = Config.Command3,
					["color"] = Config.color,
                	["description"] = msg,
                	["footer"] = {
                	["text"] = "Generated By: "..source.. "."
                	}
            	}
        	}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source, Config.Command3response)
end
		if msg ~= nil and Config.Discordis and Config.Command3responseis and Config.Command3global == false then
			local discordmessage = {
	   			{
		   			["type"] = "rich",
		   			["title"] = Config.Command3,
		   			["color"] = Config.color,
		   			["description"] = msg,
		   			["footer"] = {
		   			["text"] = "Generated By: "..source.. "."
		  			}
				}
  			}
  			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
  			TriggerClientEvent('chatMessage', source, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
  			TriggerClientEvent('chatMessage', source, Config.Command3response)
end
		if msg ~= nil and Config.Discordis and Config.Command3responseis == false and Config.Command3global then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command3,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
end
		if msg ~= nil and Config.Discordis and Config.Command3responseis == false and Config.Command3global == false then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command3,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', source, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command3responseis and Config.Command3global then
			TriggerClientEvent('chatMessage', -1, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command3response)
end
		if Config.Discordis == false and Config.Command3responseis and Config.Command3global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command3response)
end
		if Config.Discordis == false and Config.Command3responseis == false and Config.Command3global then
			TriggerClientEvent('chatMessage', -1, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command3responseis == false and Config.Command3global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command3Subject .. name, Config.Command3color, string.sub(msg,5))
		end
	end 
 end)

 -------------------------  Command 4   -------------------------

 AddEventHandler('chatMessage', function(source, name, msg)
	sm = stringsplit(msg, " ");
	if sm[1] == Config.Command4 then
		CancelEvent()
		if msg ~= nil and Config.Discordis and Config.Command4responseis and Config.Command4global then
     		local discordmessage = {
            	{
            		["type"] = "rich",
					["title"] = Config.Command4,
					["color"] = Config.color,
                	["description"] = msg,
                	["footer"] = {
                	["text"] = "Generated By: "..source.. "."
                	}
            	}
        	}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source, Config.Command4response)
end
		if msg ~= nil and Config.Discordis and Config.Command4responseis and Config.Command4global == false then
			local discordmessage = {
	   			{
		   			["type"] = "rich",
		   			["title"] = Config.Command4,
		   			["color"] = Config.color,
		   			["description"] = msg,
		   			["footer"] = {
		   			["text"] = "Generated By: "..source.. "."
		  			}
				}
  			}
  			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
  			TriggerClientEvent('chatMessage', source, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
  			TriggerClientEvent('chatMessage', source, Config.Command4response)
end
		if msg ~= nil and Config.Discordis and Config.Command4responseis == false and Config.Command4global then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command4,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
end
		if msg ~= nil and Config.Discordis and Config.Command4responseis == false and Config.Command4global == false then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command4,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', source, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command4responseis and Config.Command4global then
			TriggerClientEvent('chatMessage', -1, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command4response)
end
		if Config.Discordis == false and Config.Command4responseis and Config.Command4global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command4response)
end
		if Config.Discordis == false and Config.Command4responseis == false and Config.Command4global then
			TriggerClientEvent('chatMessage', -1, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command4responseis == false and Config.Command4global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command4Subject .. name, Config.Command4color, string.sub(msg,5))
		end
	end 
 end)

 -------------------------  Command 5   -------------------------

 AddEventHandler('chatMessage', function(source, name, msg)
	sm = stringsplit(msg, " ");
	if sm[1] == Config.Command5 then
		CancelEvent()
		if msg ~= nil and Config.Discordis and Config.Command5responseis and Config.Command5global then
     		local discordmessage = {
            	{
            		["type"] = "rich",
					["title"] = Config.Command5,
					["color"] = Config.color,
                	["description"] = msg,
                	["footer"] = {
                	["text"] = "Generated By: "..source.. "."
                	}
            	}
        	}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source, Config.Command5response)
end
		if msg ~= nil and Config.Discordis and Config.Command5responseis and Config.Command5global == false then
			local discordmessage = {
	   			{
		   			["type"] = "rich",
		   			["title"] = Config.Command5,
		   			["color"] = Config.color,
		   			["description"] = msg,
		   			["footer"] = {
		   			["text"] = "Generated By: "..source.. "."
		  			}
				}
  			}
  			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
  			TriggerClientEvent('chatMessage', source, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
  			TriggerClientEvent('chatMessage', source, Config.Command5response)
end
		if msg ~= nil and Config.Discordis and Config.Command5responseis == false and Config.Command5global then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command5,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', -1, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
end
		if msg ~= nil and Config.Discordis and Config.Command5responseis == false and Config.Command5global == false then
			local discordmessage = {
				{
					["type"] = "rich",
					["title"] = Config.Command5,
					["color"] = Config.color,
					["description"] = msg,
					["footer"] = {
					["text"] = "Generated By: "..source.. "."
					}
				}
			}
			PerformHttpRequest(Config.webHookURL, function(Error, Content, Head) end, 'POST', json.encode({embeds = discordmessage}), { ['Content-Type'] = 'application/json' })
			TriggerClientEvent('chatMessage', source, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command5responseis and Config.Command5global then
			TriggerClientEvent('chatMessage', -1, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command5response)
end
		if Config.Discordis == false and Config.Command5responseis and Config.Command5global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
			TriggerClientEvent('chatMessage', source,  Config.Command5response)
end
		if Config.Discordis == false and Config.Command5responseis == false and Config.Command5global then
			TriggerClientEvent('chatMessage', -1, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
end
		if Config.Discordis == false and Config.Command5responseis == false and Config.Command5global == false then
			TriggerClientEvent('chatMessage', -1, Config.Command5Subject .. name, Config.Command5color, string.sub(msg,5))
		end
	end 
 end)


function stringsplit(inputstr, sep)
   if sep == nil then
       sep = "%s"
    end
  local t={} ; i=1
     for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
       t[i] = str
      i = i + 1
  end
  return t
end